import { Platform, StyleSheet } from "react-native";

const colors = {
  background: "#101214",
  panel: "#171a1d",
  panelStrong: "#1b1f23",
  surface: "#20252a",
  surfaceStrong: "#262b31",
  border: "rgba(255, 255, 255, 0.09)",
  borderStrong: "rgba(234, 111, 63, 0.3)",
  brand: "#ea6f3f",
  brandPressed: "#d66034",
  brandSoft: "rgba(234, 111, 63, 0.14)",
  brandMuted: "rgba(234, 111, 63, 0.12)",
  textPrimary: "#f5f7fa",
  textSecondary: "#c8ced6",
  textMuted: "#8d98a4",
  textSoft: "#ffd9c9",
  placeholder: "#707b86",
  inputBackground: "#14181c",
  inputBorder: "rgba(255, 255, 255, 0.09)",
  successBorder: "rgba(124, 230, 191, 0.34)",
  successBackground: "rgba(21, 67, 50, 0.44)",
  warningBorder: "rgba(255, 210, 139, 0.36)",
  warningBackground: "rgba(82, 56, 21, 0.44)",
  errorBorder: "rgba(253, 164, 175, 0.34)",
  errorBackground: "rgba(88, 29, 37, 0.44)",
  errorText: "#fecdd3",
};

const displayFontFamily = Platform.select({
  ios: undefined,
  android: undefined,
  default: undefined,
});

const panelShadow = {
  shadowColor: "#000000",
  shadowOpacity: 0.16,
  shadowRadius: 14,
  shadowOffset: { width: 0, height: 8 },
  elevation: 4,
} as const;

const brandShadow = {
  shadowColor: colors.brand,
  shadowOpacity: 0.18,
  shadowRadius: 12,
  shadowOffset: { width: 0, height: 6 },
  elevation: 3,
} as const;

export const theme = {
  colors,
  displayFontFamily,
};

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
    position: "relative",
  },
  keyboardShell: {
    flex: 1,
  },
  backgroundOrbTop: {
    position: "absolute",
    top: -160,
    right: -120,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: "rgba(255, 173, 112, 0.08)",
  },
  backgroundOrbLeft: {
    position: "absolute",
    top: 160,
    left: -150,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: "rgba(234, 111, 63, 0.07)",
  },
  backgroundOrbRight: {
    position: "absolute",
    bottom: 120,
    right: -150,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: "rgba(255, 204, 156, 0.05)",
  },
  loadingScreen: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.background,
    gap: 12,
  },
  loadingText: {
    color: colors.textSecondary,
    fontSize: 16,
  },
  content: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 28,
    gap: 14,
  },
  heroCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.panelStrong,
    padding: 18,
    gap: 12,
    overflow: "hidden",
  },
  heroGlow: {
    position: "absolute",
    top: -64,
    right: -48,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: "rgba(255, 183, 132, 0.08)",
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  brandMark: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.brand,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.14)",
    ...brandShadow,
  },
  brandMarkText: {
    color: "#170c0a",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  brandCopy: {
    flex: 1,
    gap: 4,
  },
  eyebrow: {
    alignSelf: "flex-start",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.brandSoft,
    paddingHorizontal: 10,
    paddingVertical: 6,
    color: colors.textSoft,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.3,
    textTransform: "uppercase",
    overflow: "hidden",
  },
  brandName: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "700",
  },
  title: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: "600",
    lineHeight: 33,
    letterSpacing: -0.5,
    fontFamily: displayFontFamily,
  },
  subtitle: {
    color: colors.textSecondary,
    fontSize: 15,
    lineHeight: 22,
    maxWidth: 560,
  },
  heroSignalRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  heroSignalChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  heroSignalText: {
    color: colors.textSoft,
    fontSize: 11,
    fontWeight: "600",
  },
  stepGrid: {
    gap: 12,
  },
  stepCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.panel,
    padding: 14,
    gap: 10,
    ...panelShadow,
  },
  stepNumber: {
    alignSelf: "flex-start",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.brandMuted,
    paddingHorizontal: 10,
    paddingVertical: 6,
    color: colors.textSoft,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.4,
    textTransform: "uppercase",
    overflow: "hidden",
  },
  stepTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "700",
  },
  stepBody: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  card: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.panel,
    padding: 16,
    gap: 12,
    ...panelShadow,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: "600",
    lineHeight: 24,
    letterSpacing: -0.2,
    fontFamily: displayFontFamily,
  },
  sectionBody: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 20,
  },
  fieldBlock: {
    gap: 7,
  },
  checkboxCard: {
    flexDirection: "row",
    gap: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.inputBackground,
    padding: 14,
  },
  checkboxBox: {
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  checkboxBoxChecked: {
    borderColor: colors.borderStrong,
    backgroundColor: colors.brandSoft,
  },
  checkboxMark: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: "700",
  },
  checkboxCopy: {
    flex: 1,
    gap: 4,
  },
  label: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "600",
  },
  inlineLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  inlineAction: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  input: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: colors.inputBackground,
    color: colors.textPrimary,
    fontSize: 16,
  },
  composerInput: {
    minHeight: 108,
    textAlignVertical: "top",
  },
  inputError: {
    borderColor: colors.errorBorder,
  },
  helper: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  errorText: {
    color: colors.errorText,
    fontSize: 13,
    lineHeight: 18,
  },
  infoCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 14,
    gap: 7,
  },
  infoTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  infoBody: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 20,
  },
  primaryButton: {
    minHeight: 48,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.brand,
    paddingHorizontal: 16,
    ...brandShadow,
  },
  primaryButtonPressed: {
    opacity: 0.96,
    backgroundColor: colors.brandPressed,
    transform: [{ translateY: 1 }],
  },
  primaryButtonDisabled: {
    opacity: 0.48,
  },
  primaryButtonLabel: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "700",
  },
  secondaryButton: {
    minHeight: 46,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
  },
  secondaryButtonPressed: {
    opacity: 0.92,
    transform: [{ translateY: 1 }],
  },
  secondaryButtonLabel: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "600",
  },
  tertiaryButton: {
    alignSelf: "flex-start",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.inputBackground,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  tertiaryButtonLabel: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: "700",
  },
  devButton: {
    marginTop: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.brandSoft,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  devButtonLabel: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: "700",
  },
  bullet: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 22,
  },
  statusCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 12,
    gap: 6,
  },
  statusCardWarning: {
    borderColor: colors.warningBorder,
    backgroundColor: colors.warningBackground,
  },
  statusCardError: {
    borderColor: colors.errorBorder,
    backgroundColor: colors.errorBackground,
  },
  statusCardSuccess: {
    borderColor: colors.successBorder,
    backgroundColor: colors.successBackground,
  },
  statusTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "700",
  },
  statusBody: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 20,
  },
  metricRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  metricCard: {
    flex: 1,
    minWidth: 150,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 12,
    gap: 6,
  },
  sessionList: {
    gap: 10,
  },
  sessionRow: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 12,
    gap: 6,
  },
  sessionRowTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  sessionRowTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  sessionCurrentBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.brandSoft,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  sessionCurrentBadgeLabel: {
    color: colors.textSoft,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  sessionRowMeta: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  deviceLinkCard: {
    gap: 12,
  },
  qrScannerCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 12,
    gap: 10,
  },
  qrScannerFrame: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: "#000000",
  },
  qrDisplayCard: {
    alignItems: "center",
    gap: 10,
  },
  qrDisplaySurface: {
    borderRadius: 20,
    backgroundColor: "#ffffff",
    padding: 16,
  },
  deviceLinkStatusCard: {
    gap: 10,
  },
  metricLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.9,
    textTransform: "uppercase",
  },
  metricValue: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: "700",
  },
  metricValueText: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "700",
  },
  segmentRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  segmentButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.inputBackground,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  segmentButtonActive: {
    borderColor: colors.borderStrong,
    backgroundColor: colors.brandSoft,
  },
  segmentButtonLabel: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  segmentButtonLabelActive: {
    color: colors.textSoft,
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    paddingVertical: 6,
  },
  toggleTextBlock: {
    flex: 1,
    gap: 4,
  },
  toggleTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "600",
  },
  toggleDescription: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  toggleTrack: {
    width: 50,
    height: 30,
    borderRadius: 999,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    padding: 4,
    justifyContent: "center",
  },
  toggleTrackOn: {
    backgroundColor: "rgba(234, 111, 63, 0.38)",
  },
  toggleThumb: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#f0dbd0",
  },
  toggleThumbOn: {
    alignSelf: "flex-end",
    backgroundColor: colors.textPrimary,
  },
  buttonRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  buttonRowButton: {
    flex: 1,
    minWidth: 150,
  },
  codeText: {
    color: colors.textSoft,
    fontSize: 12,
    lineHeight: 18,
  },
  inlineLoadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  groupSelectorRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  groupSelectorChip: {
    minWidth: 132,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.inputBackground,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  groupSelectorChipActive: {
    borderColor: colors.borderStrong,
    backgroundColor: colors.brandSoft,
  },
  groupSelectorLabel: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  groupSelectorLabelActive: {
    color: colors.textSoft,
  },
  groupSelectorMeta: {
    color: colors.textMuted,
    fontSize: 12,
  },
  threadMetaRow: {
    gap: 4,
  },
  threadMetaText: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  threadList: {
    gap: 10,
  },
  messageRow: {
    flexDirection: "row",
  },
  messageRowOwn: {
    justifyContent: "flex-end",
  },
  messageBubble: {
    maxWidth: "88%",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 12,
    gap: 6,
  },
  messageBubbleOwn: {
    borderColor: colors.borderStrong,
    backgroundColor: colors.brandSoft,
  },
  skeletonBubble: {
    maxWidth: "75%",
    height: 60,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    marginBottom: 8,
  },
  skeletonBubbleSoft: {
    opacity: 0.6,
    width: "60%",
  },
  skeletonBubbleFaint: {
    opacity: 0.3,
    width: "40%",
  },
  messageMeta: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "600",
  },
  messageText: {
    color: colors.textPrimary,
    fontSize: 15,
    lineHeight: 21,
  },
  attachmentMeta: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  messageImage: {
    width: "100%",
    minHeight: 220,
    borderRadius: 16,
    backgroundColor: colors.inputBackground,
  },
  attachmentActionGroup: {
    gap: 8,
  },
  attachmentActionButton: {
    alignSelf: "flex-start",
    minWidth: 148,
  },
  locationCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.panel,
    overflow: "hidden",
  },
  locationMapFrame: {
    position: "relative",
    width: "100%",
    aspectRatio: 16 / 9,
    backgroundColor: colors.inputBackground,
  },
  locationMapImage: {
    width: "100%",
    height: "100%",
  },
  locationMapMarker: {
    position: "absolute",
    width: 18,
    height: 18,
    marginLeft: -9,
    marginTop: -9,
    borderRadius: 999,
    borderWidth: 3,
    borderColor: "#ffffff",
    backgroundColor: colors.brand,
  },
  locationCardBody: {
    paddingHorizontal: 12,
    paddingVertical: 11,
    gap: 4,
  },
  locationTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "700",
  },
  locationDetail: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  locationActionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    marginTop: 4,
  },
  locationActionLabel: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: "700",
  },
  locationAttribution: {
    flex: 1,
    color: colors.textMuted,
    fontSize: 11,
    textAlign: "right",
  },
  systemMessageCard: {
    alignSelf: "center",
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  systemMessageText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "600",
  },
  emptyThreadCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 12,
    gap: 6,
  },
  pendingAttachmentCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 12,
    gap: 10,
  },
  pendingAttachmentHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  pendingAttachmentImage: {
    width: "100%",
    height: 180,
    borderRadius: 16,
    backgroundColor: colors.inputBackground,
  },
  appShell: {
    flex: 1,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 12,
    gap: 12,
  },
  shellBanner: {
    gap: 8,
  },
  appBody: {
    flex: 1,
  },
  appTabBar: {
    flexDirection: "row",
    gap: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.panel,
    borderRadius: 18,
    padding: 8,
  },
  appTabButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    paddingVertical: 12,
    backgroundColor: colors.surface,
  },
  appTabButtonActive: {
    backgroundColor: colors.brandSoft,
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  appTabLabel: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: "700",
  },
  appTabLabelActive: {
    color: colors.textSoft,
  },
  screenSection: {
    flex: 1,
    gap: 12,
  },
  screenScroll: {
    flex: 1,
  },
  screenScrollContent: {
    gap: 12,
    paddingBottom: 20,
  },
  screenHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  screenHeader: {
    flex: 1,
    gap: 4,
    paddingHorizontal: 2,
  },
  screenHeaderActionSlot: {
    paddingTop: 2,
  },
  screenHeaderActionButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.brandSoft,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  screenHeaderActionLabel: {
    color: colors.textSoft,
    fontSize: 12,
    fontWeight: "700",
  },
  resumeCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.brandMuted,
    padding: 14,
    gap: 8,
  },
  resumeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  resumeEyebrow: {
    color: colors.textSoft,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  resumeTimestamp: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: "600",
  },
  resumeTitle: {
    color: colors.textPrimary,
    fontSize: 17,
    fontWeight: "700",
  },
  resumePreview: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  resumeFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  resumeAction: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: "700",
  },
  resumeEmptyCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.panel,
    padding: 14,
    gap: 8,
  },
  resumeEmptyTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "700",
  },
  resumeEmptyBody: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  screenTitle: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: "700",
    letterSpacing: -0.3,
  },
  screenSubtitle: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  searchInput: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.inputBackground,
    paddingHorizontal: 16,
    paddingVertical: 13,
    color: colors.textPrimary,
    fontSize: 15,
  },
  filterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  filterChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.inputBackground,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  filterChipActive: {
    borderColor: colors.borderStrong,
    backgroundColor: colors.brandSoft,
  },
  filterLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "capitalize",
  },
  filterLabelActive: {
    color: colors.textSoft,
  },
  chatRow: {
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.panel,
    padding: 14,
  },
  chatRowActive: {
    borderColor: colors.borderStrong,
    backgroundColor: colors.brandSoft,
  },
  chatAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceStrong,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chatAvatarText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "700",
  },
  chatRowCopy: {
    flex: 1,
    gap: 6,
  },
  chatRowTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  chatRowTitle: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "700",
  },
  chatRowTime: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: "600",
  },
  chatRowPreview: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  chatMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
  },
  chatRowMeta: {
    color: colors.textMuted,
    fontSize: 12,
  },
  chatBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceStrong,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  chatBadgeText: {
    color: colors.textSoft,
    fontSize: 11,
    fontWeight: "700",
  },
  unreadBadge: {
    borderRadius: 999,
    minWidth: 24,
    paddingHorizontal: 8,
    paddingVertical: 3,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.brand,
  },
  unreadBadgeText: {
    color: "#1b0d08",
    fontSize: 11,
    fontWeight: "800",
  },
  emptyState: {
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.panel,
    padding: 16,
  },
  emptyStateTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "700",
  },
  emptyStateBody: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  conversationShell: {
    flex: 1,
    gap: 12,
  },
  conversationHeader: {
    gap: 8,
  },
  backButton: {
    alignSelf: "flex-start",
    paddingVertical: 4,
  },
  backButtonLabel: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: "700",
  },
  conversationHeaderCopy: {
    gap: 4,
  },
  conversationTitle: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: "700",
    letterSpacing: -0.3,
  },
  conversationSubtitle: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  conversationMessages: {
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.panel,
    padding: 12,
  },
  conversationMessagesContent: {
    gap: 10,
    paddingBottom: 8,
  },
  conversationComposer: {
    gap: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.panel,
    padding: 12,
  },
  composerInputCompact: {
    minHeight: 86,
    textAlignVertical: "top",
  },
  composerActionsRow: {
    flexDirection: "row",
    gap: 10,
  },
  composerSendButton: {
    minWidth: 92,
  },

  // ---- image viewer ----
  imageViewerOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.96)",
    alignItems: "center",
    justifyContent: "center",
  },
  imageViewerCloseButton: {
    position: "absolute",
    top: 52,
    right: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  imageViewerCloseText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "700",
  },
  imageViewerError: {
    alignItems: "center",
    paddingHorizontal: 32,
    gap: 8,
  },
  imageViewerStatus: {
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 28,
  },
  imageViewerStatusText: {
    color: colors.textSecondary,
    fontSize: 14,
    textAlign: "center",
    lineHeight: 21,
  },
  imageViewerErrorText: {
    color: colors.errorText,
    fontSize: 14,
    textAlign: "center",
    lineHeight: 21,
  },

  // ---- message context menu ----
  contextMenuOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.55)",
    justifyContent: "flex-end",
  },
  contextMenuSheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: colors.panelStrong,
    borderTopWidth: 1,
    borderColor: colors.border,
    paddingBottom: 36,
    paddingTop: 12,
  },
  contextMenuDrag: {
    alignSelf: "center",
    width: 44,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.border,
    marginBottom: 12,
  },
  contextMenuItem: {
    paddingHorizontal: 24,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  contextMenuItemLabel: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  contextMenuItemDestructive: {
    color: colors.errorText,
  },
  contextMenuDivider: {
    height: 1,
    backgroundColor: colors.border,
    marginHorizontal: 20,
  },

  // ---- format toolbar ----
  formatToolbar: {
    flexDirection: "row",
    gap: 6,
    paddingBottom: 4,
  },
  formatButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.inputBackground,
    alignItems: "center",
    justifyContent: "center",
  },
  formatButtonActive: {
    borderColor: colors.borderStrong,
    backgroundColor: colors.brandSoft,
  },
  formatButtonLabel: {
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: "700",
  },
  formatButtonLabelActive: {
    color: colors.textSoft,
  },
  editModeBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.brandSoft,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  editModeBannerText: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: "600",
  },

  // ---- group settings modal ----
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  modalSheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: colors.panelStrong,
    borderTopWidth: 1,
    borderColor: colors.border,
    padding: 20,
    paddingBottom: 36,
    gap: 16,
  },
  modalTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: "700",
    letterSpacing: -0.2,
  },
  inviteLinkBox: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.inputBackground,
    padding: 12,
    gap: 6,
  },

  // ---- profile avatar ----
  avatarCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.surfaceStrong,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarImage: {
    width: 64,
    height: 64,
    borderRadius: 32,
  },
  avatarInitials: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "700",
  },
  avatarRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  editedLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontStyle: "italic",
  },
  sentTick: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: "600",
    marginLeft: 4,
  },
  unreadDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.brand,
    marginLeft: "auto" as unknown as number,
    alignSelf: "center",
  },

  // ---- swipeable chat row ----
  chatRowShell: {
    position: "relative",
    marginBottom: 4,
    overflow: "hidden",
    borderRadius: 18,
  },
  chatRowActions: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    alignItems: "stretch",
  },
  chatActionButton: {
    alignItems: "center",
    justifyContent: "center",
    width: 80,
    paddingHorizontal: 8,
  },
  chatActionButtonMuted: {
    backgroundColor: "#2d3748",
  },
  chatActionButtonPinned: {
    backgroundColor: "#44380c",
  },
  chatActionButtonArchived: {
    backgroundColor: "#1a2430",
  },
  chatActionLabel: {
    color: colors.textSoft,
    fontSize: 12,
    fontWeight: "700",
  },
  chatRowAnimated: {
    backgroundColor: colors.background,
    borderRadius: 18,
  },
  chatRowTitleUnread: {
    color: "#ffffff",
    fontWeight: "800",
  },
  chatRowRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  chatRowTimeUnread: {
    color: colors.textSoft,
  },
  chatStateLabel: {
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  chatRowPreviewUnread: {
    color: colors.textPrimary,
  },
  chatListContent: {
    gap: 4,
    paddingBottom: 24,
  },
  chatWorkspaceShell: {
    flex: 1,
    flexDirection: "row",
    gap: 12,
  },
  chatWorkspaceListPane: {
    flex: 0.95,
    minWidth: 320,
    maxWidth: 420,
  },
  chatWorkspaceDetailPane: {
    flex: 1.35,
  },
  chatWorkspaceEmptyPane: {
    flex: 1,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.panel,
    padding: 24,
    justifyContent: "center",
    gap: 10,
  },
  chatWorkspaceEmptyTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "700",
  },
  chatWorkspaceEmptyBody: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 22,
    maxWidth: 420,
  },

  // ---- conversation top bar ----
  conversationTopBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingBottom: 2,
  },
  conversationIdentity: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    overflow: "hidden",
  },
  conversationAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceStrong,
    borderWidth: 1,
    borderColor: colors.border,
    flexShrink: 0,
  },
  conversationAvatarText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  conversationOverflowButton: {
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  conversationOverflowLabel: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: "700",
  },
  conversationLoadingState: {
    alignItems: "flex-start",
    justifyContent: "flex-end",
  },
  attachmentRetryButton: {
    alignSelf: "flex-start",
    paddingVertical: 2,
  },
  attachmentRetryLabel: {
    color: colors.textSoft,
    fontSize: 12,
    fontWeight: "700",
  },

  // ---- date separator ----
  dateSeparator: {
    alignItems: "center",
    paddingVertical: 6,
  },
  dateSeparatorLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.4,
  },

  // ---- docked composer ----
  composerDock: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 6,
  },
  composerAttachColumn: {
    flexDirection: "column",
    gap: 6,
    flexShrink: 0,
  },
  composerAttachButton: {
    width: 46,
    height: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.inputBackground,
    alignItems: "center",
    justifyContent: "center",
  },
  composerAttachLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: "700",
  },
  composerInputDocked: {
    flex: 1,
    minHeight: 40,
    maxHeight: 140,
    textAlignVertical: "top",
    paddingTop: 9,
    paddingBottom: 9,
    paddingHorizontal: 4,
  },
  composerSendButtonDocked: {
    minWidth: 64,
    height: 46,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.brand,
    paddingHorizontal: 12,
    flexShrink: 0,
  },
  composerSendButtonLabel: {
    color: "#1b0d08",
    fontSize: 14,
    fontWeight: "800",
  },
  // Telegram-style icon buttons
  composerIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.inputBackground,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    marginBottom: 2,
  },
  composerIconButtonDisabled: {
    opacity: 0.4,
  },
  composerIconLabel: {
    fontSize: 17,
    lineHeight: 20,
  },
  composerSendCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.brand,
    flexShrink: 0,
    marginBottom: 2,
  },
  composerSendCircleDisabled: {
    opacity: 0.45,
  },
  composerSendIcon: {
    color: "#1b0d08",
    fontSize: 20,
    fontWeight: "900",
    lineHeight: 22,
  },

  // ---- member roster modal ----
  memberRosterSheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: colors.panelStrong,
    borderTopWidth: 1,
    borderColor: colors.border,
    padding: 20,
    paddingBottom: 48,
    gap: 16,
    minHeight: 300,
    maxHeight: "85%",
  },
  memberRosterScroll: {
    flexGrow: 0,
  },
  memberRosterLoading: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 12,
  },
  memberRosterLoadingText: {
    color: colors.textMuted,
    fontSize: 14,
  },
  memberRosterList: {
    gap: 4,
  },
  memberRosterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderRadius: 12,
  },
  memberRosterAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceStrong,
    borderWidth: 1,
    borderColor: colors.border,
    flexShrink: 0,
  },
  memberRosterAvatarText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  memberRosterCopy: {
    flex: 1,
    gap: 2,
  },
  memberRosterName: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "600",
  },
  memberRosterMeta: {
    color: colors.textMuted,
    fontSize: 12,
  },
  memberRosterChevron: {
    color: colors.textMuted,
    fontSize: 22,
    fontWeight: "300",
    marginLeft: 4,
  },

  // ---- member profile sheet ----
  memberProfileSheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: colors.panelStrong,
    borderTopWidth: 1,
    borderColor: colors.border,
    padding: 20,
    paddingBottom: 48,
    gap: 18,
    maxHeight: "90%",
  },
  memberProfileDrag: {
    alignSelf: "center",
    width: 44,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.border,
    marginBottom: 4,
  },
  memberProfileHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  memberProfileAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceStrong,
    borderWidth: 1,
    borderColor: colors.border,
    flexShrink: 0,
  },
  memberProfileAvatarText: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: "700",
  },
  memberProfileHeaderCopy: {
    flex: 1,
    gap: 6,
  },
  memberProfileName: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: "700",
    letterSpacing: -0.2,
  },
  memberProfileRoleRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
  },
  memberProfileMeta: {
    flexDirection: "row",
    gap: 14,
    flexWrap: "wrap",
  },
  memberProfileMetaText: {
    color: colors.textMuted,
    fontSize: 12,
  },

  // ---- role badge ----
  roleBadge: {
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderWidth: 1,
  },
  roleBadgeOwner: {
    borderColor: "rgba(234, 111, 63, 0.45)",
    backgroundColor: "rgba(234, 111, 63, 0.12)",
  },
  roleBadgeAdmin: {
    borderColor: "rgba(168, 139, 250, 0.4)",
    backgroundColor: "rgba(168, 139, 250, 0.1)",
  },
  roleBadgeMember: {
    borderColor: colors.border,
    backgroundColor: colors.surfaceStrong,
  },
  roleBadgeSelf: {
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: colors.successBorder,
    backgroundColor: colors.successBackground,
  },
  roleBadgeLabel: {
    color: colors.textSoft,
    fontSize: 11,
    fontWeight: "700",
  },

  // ---- member activity section ----
  memberActivitySection: {
    gap: 8,
  },
  memberActivityLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  memberActivityRow: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  memberActivityText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },

  // ---- member notes section ----
  memberNotesSection: {
    gap: 10,
  },
  memberNotesTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  memberNotesTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  memberNotesHint: {
    color: colors.textMuted,
    fontSize: 11,
  },
  memberNotesInput: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.inputBackground,
    padding: 12,
    color: colors.textPrimary,
    fontSize: 14,
    lineHeight: 21,
    textAlignVertical: "top",
    minHeight: 80,
  },

  // ---- member profile action buttons ----
  memberProfileActions: {
    gap: 10,
  },

  // ---- attach menu sheet ----
  attachMenuSheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: colors.panelStrong,
    borderTopWidth: 1,
    borderColor: colors.border,
    paddingBottom: 32,
    paddingTop: 12,
    gap: 14,
  },
  attachCameraPreview: {
    marginHorizontal: 16,
    height: 170,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: colors.surface,
    position: "relative",
  },
  attachCameraPlaceholder: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  attachCameraPlaceholderIcon: {
    fontSize: 40,
  },
  attachCameraPlaceholderLabel: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: "600",
  },
  attachCameraHintBadge: {
    position: "absolute",
    bottom: 10,
    left: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: "rgba(0,0,0,0.55)",
  },
  attachCameraHintText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "600",
  },
  attachGrid: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingHorizontal: 8,
  },
  attachGridTile: {
    alignItems: "center",
    gap: 6,
    flex: 1,
  },
  attachGridIconCircle: {
    width: 58,
    height: 58,
    borderRadius: 29,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  attachGridIconText: {
    fontSize: 24,
  },
  attachGridLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "600",
    textAlign: "center",
  },

  // ---- attach sub-sheets (location / poll / checklist) ----
  attachSubSheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: colors.panelStrong,
    borderTopWidth: 1,
    borderColor: colors.border,
    paddingBottom: 32,
    paddingTop: 12,
    paddingHorizontal: 20,
    gap: 16,
    maxHeight: "85%",
  },
  attachSubSheetTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: -0.2,
  },
  attachSubSheetScroll: {
    maxHeight: 340,
  },
  attachSubSheetInput: {
    marginBottom: 10,
  },
  attachSubSheetOption: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 14,
    paddingVertical: 12,
  },
  attachSubSheetOptionIcon: {
    fontSize: 24,
    lineHeight: 28,
  },
  attachSubSheetOptionCopy: {
    gap: 3,
  },
  attachSubSheetOptionLabel: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "700",
  },
  attachSubSheetOptionHint: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },

  // duration chips (live location)
  attachDurationRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
    flexWrap: "wrap",
  },
  attachDurationChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.inputBackground,
  },
  attachDurationChipActive: {
    borderColor: colors.borderStrong,
    backgroundColor: colors.brandSoft,
  },
  attachDurationChipLabel: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: "600",
  },
  attachDurationChipLabelActive: {
    color: colors.textSoft,
  },

  // poll / checklist option rows
  attachPollOptionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  attachPollRemove: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    flexShrink: 0,
  },
  attachPollRemoveLabel: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: "700",
  },
  attachCheckPrefix: {
    color: colors.textSecondary,
    fontSize: 18,
    lineHeight: 44,
    flexShrink: 0,
  },
});
