import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#071116",
  },
  keyboardShell: {
    flex: 1,
  },
  loadingScreen: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#071116",
    gap: 12,
  },
  loadingText: {
    color: "#eaf4f4",
    fontSize: 16,
  },
  content: {
    paddingHorizontal: 20,
    paddingVertical: 28,
    gap: 16,
  },
  eyebrow: {
    color: "#91f3d8",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.6,
    textTransform: "uppercase",
  },
  title: {
    color: "#f7fafc",
    fontSize: 34,
    fontWeight: "700",
    lineHeight: 40,
  },
  subtitle: {
    color: "#b6c8cc",
    fontSize: 16,
    lineHeight: 24,
    maxWidth: 560,
  },
  stepGrid: {
    gap: 12,
  },
  stepCard: {
    backgroundColor: "#0b171d",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#17303a",
    padding: 16,
    gap: 6,
  },
  stepNumber: {
    color: "#91f3d8",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.6,
    textTransform: "uppercase",
  },
  stepTitle: {
    color: "#f7fafc",
    fontSize: 15,
    fontWeight: "600",
  },
  stepBody: {
    color: "#b6c8cc",
    fontSize: 14,
    lineHeight: 20,
  },
  card: {
    backgroundColor: "#0f1a21",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#17303a",
    padding: 18,
    gap: 12,
  },
  sectionTitle: {
    color: "#f7fafc",
    fontSize: 18,
    fontWeight: "600",
  },
  sectionBody: {
    color: "#b6c8cc",
    fontSize: 14,
    lineHeight: 21,
  },
  fieldBlock: {
    gap: 6,
  },
  checkboxCard: {
    flexDirection: "row",
    gap: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#1f3b46",
    backgroundColor: "#081419",
    padding: 14,
  },
  checkboxBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#45616a",
    backgroundColor: "#081419",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  checkboxBoxChecked: {
    borderColor: "#91f3d8",
    backgroundColor: "#10302c",
  },
  checkboxMark: {
    color: "#91f3d8",
    fontSize: 13,
    fontWeight: "700",
  },
  checkboxCopy: {
    flex: 1,
    gap: 4,
  },
  label: {
    color: "#f7fafc",
    fontSize: 14,
    fontWeight: "600",
  },
  inlineLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  inlineAction: {
    color: "#91f3d8",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  input: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#1f3b46",
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: "#081419",
    color: "#f7fafc",
    fontSize: 16,
  },
  composerInput: {
    minHeight: 108,
    textAlignVertical: "top",
  },
  inputError: {
    borderColor: "#ef4444",
  },
  helper: {
    color: "#8ba1a3",
    fontSize: 12,
    lineHeight: 18,
  },
  errorText: {
    color: "#fda4af",
    fontSize: 13,
    lineHeight: 18,
  },
  infoCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#1f3b46",
    borderStyle: "dashed",
    backgroundColor: "#0a151a",
    padding: 14,
    gap: 6,
  },
  infoTitle: {
    color: "#f7fafc",
    fontSize: 14,
    fontWeight: "600",
  },
  infoBody: {
    color: "#b6c8cc",
    fontSize: 13,
    lineHeight: 20,
  },
  primaryButton: {
    minHeight: 52,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#91f3d8",
    paddingHorizontal: 16,
  },
  primaryButtonPressed: {
    opacity: 0.88,
  },
  primaryButtonDisabled: {
    opacity: 0.5,
  },
  primaryButtonLabel: {
    color: "#06242b",
    fontSize: 16,
    fontWeight: "700",
  },
  secondaryButton: {
    minHeight: 48,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#1f3b46",
    backgroundColor: "#081419",
    paddingHorizontal: 16,
  },
  secondaryButtonLabel: {
    color: "#f7fafc",
    fontSize: 15,
    fontWeight: "600",
  },
  devButton: {
    marginTop: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#1f5b4a",
    backgroundColor: "#0c1d18",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  devButtonLabel: {
    color: "#91f3d8",
    fontSize: 13,
    fontWeight: "700",
  },
  bullet: {
    color: "#b6c8cc",
    fontSize: 14,
    lineHeight: 22,
  },
  statusCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#1f3b46",
    backgroundColor: "#0b171d",
    padding: 14,
    gap: 6,
  },
  statusCardWarning: {
    borderColor: "#b8791f",
    backgroundColor: "#2b2210",
  },
  statusCardError: {
    borderColor: "#7f1d1d",
    backgroundColor: "#261113",
  },
  statusCardSuccess: {
    borderColor: "#1f5b4a",
    backgroundColor: "#0d221c",
  },
  statusTitle: {
    color: "#f7fafc",
    fontSize: 15,
    fontWeight: "600",
  },
  statusBody: {
    color: "#b6c8cc",
    fontSize: 13,
    lineHeight: 20,
  },
  metricRow: {
    flexDirection: "row",
    gap: 12,
  },
  metricCard: {
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#17303a",
    backgroundColor: "#0b171d",
    padding: 14,
    gap: 6,
  },
  metricLabel: {
    color: "#8ba1a3",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  metricValue: {
    color: "#f7fafc",
    fontSize: 22,
    fontWeight: "700",
  },
  metricValueText: {
    color: "#f7fafc",
    fontSize: 15,
    fontWeight: "700",
  },
  segmentRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  segmentButton: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#1f3b46",
    backgroundColor: "#081419",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  segmentButtonActive: {
    borderColor: "#91f3d8",
    backgroundColor: "#0f2621",
  },
  segmentButtonLabel: {
    color: "#8ba1a3",
    fontSize: 13,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  segmentButtonLabelActive: {
    color: "#91f3d8",
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    paddingVertical: 6,
  },
  toggleTextBlock: {
    flex: 1,
    gap: 4,
  },
  toggleTitle: {
    color: "#f7fafc",
    fontSize: 14,
    fontWeight: "600",
  },
  toggleDescription: {
    color: "#8ba1a3",
    fontSize: 12,
    lineHeight: 18,
  },
  toggleTrack: {
    width: 48,
    height: 28,
    borderRadius: 999,
    backgroundColor: "#21353d",
    padding: 3,
    justifyContent: "center",
  },
  toggleTrackOn: {
    backgroundColor: "#1f5b4a",
  },
  toggleThumb: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#dbe6e7",
  },
  toggleThumbOn: {
    alignSelf: "flex-end",
    backgroundColor: "#91f3d8",
  },
  buttonRow: {
    flexDirection: "row",
    gap: 10,
  },
  buttonRowButton: {
    flex: 1,
  },
  codeText: {
    color: "#91f3d8",
    fontSize: 12,
    lineHeight: 18,
  },
  inlineLoadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  groupSelectorRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  groupSelectorChip: {
    minWidth: 132,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#1f3b46",
    backgroundColor: "#081419",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  groupSelectorChipActive: {
    borderColor: "#91f3d8",
    backgroundColor: "#0f2621",
  },
  groupSelectorLabel: {
    color: "#f7fafc",
    fontSize: 14,
    fontWeight: "700",
  },
  groupSelectorLabelActive: {
    color: "#91f3d8",
  },
  groupSelectorMeta: {
    color: "#8ba1a3",
    fontSize: 12,
  },
  threadMetaRow: {
    gap: 4,
  },
  threadMetaText: {
    color: "#8ba1a3",
    fontSize: 12,
    lineHeight: 18,
  },
  threadList: {
    gap: 10,
  },
  messageRow: {
    flexDirection: "row",
  },
  messageRowOwn: {
    justifyContent: "flex-end",
  },
  messageBubble: {
    maxWidth: "88%",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#17303a",
    backgroundColor: "#0b171d",
    padding: 12,
    gap: 6,
  },
  messageBubbleOwn: {
    borderColor: "#1f5b4a",
    backgroundColor: "#0f2621",
  },
  messageMeta: {
    color: "#8ba1a3",
    fontSize: 12,
    fontWeight: "600",
  },
  messageText: {
    color: "#f7fafc",
    fontSize: 15,
    lineHeight: 21,
  },
  attachmentMeta: {
    color: "#8ba1a3",
    fontSize: 12,
    lineHeight: 18,
  },
  messageImage: {
    width: "100%",
    minHeight: 220,
    borderRadius: 14,
    backgroundColor: "#081419",
  },
  systemMessageCard: {
    alignSelf: "center",
    borderRadius: 999,
    backgroundColor: "#0b171d",
    borderWidth: 1,
    borderColor: "#17303a",
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  systemMessageText: {
    color: "#8ba1a3",
    fontSize: 12,
    fontWeight: "600",
  },
  emptyThreadCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#17303a",
    backgroundColor: "#0b171d",
    padding: 14,
    gap: 6,
  },
  pendingAttachmentCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#1f3b46",
    backgroundColor: "#0b171d",
    padding: 12,
    gap: 10,
  },
  pendingAttachmentHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  pendingAttachmentImage: {
    width: "100%",
    height: 220,
    borderRadius: 16,
    backgroundColor: "#081419",
  },
  selfiePickerArea: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#1f3b46",
    borderStyle: "dashed",
    overflow: "hidden",
    alignItems: "center",
    minHeight: 200,
    justifyContent: "center",
    backgroundColor: "#081419",
    gap: 10,
    padding: 16,
  },
  selfiePreview: {
    width: "100%",
    height: 240,
    borderRadius: 14,
    backgroundColor: "#081419",
  },
  selfiePlaceholder: {
    alignItems: "center",
    gap: 8,
    paddingVertical: 24,
  },
  selfiePlaceholderIcon: {
    fontSize: 40,
  },
  selfiePickerLabel: {
    color: "#f7fafc",
    fontSize: 15,
    fontWeight: "600",
  },
});
